version: '3.8'
services:
  api-geteway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: devkh-api_gateway-service
    ports:
      - "9090:9090"
    depends_on:
      - config-server
      - identity-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: futter
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: devkh-config-server
    ports:
      - "8888:8888"

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: devkh-eureka-server
    ports:
      - "8761:8761"

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    container_name: devkh-catalog-service
    ports:
      - "8085:8085"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/

  content-creator-service:
    build:
      context: ./content-creator-service
      dockerfile: Dockerfile
    container_name: devkh-content-creator-service
    ports:
      - "8087:8087"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/

  course-service:
    build:
      context: ./course-service
      dockerfile: Dockerfile
    container_name: devkh-course-service
    ports:
      - "8086:8086"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/
      SPRING_BOOTSTRAP-SERVERS: http://broker:9092/

  forum-service:
    build:
      context: ./forum-service
      dockerfile: Dockerfile
    container_name: devkh-forum-service
    ports:
      - "8096:8096"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/

  learning-service:
    build:
      context: ./learning-service
      dockerfile: Dockerfile
    container_name: devkh-learning-service
    ports:
      - "8089:8089"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    container_name: devkh-identity-service
    ports:
      - "9000:9000"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/

  rate-review-service:
    build:
      context: ./rate-review-service
      dockerfile: Dockerfile
    container_name: devkh-rate-review-service
    ports:
      - "8088:8088"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/

  media-service:
    build:
      context: ./media-service
      dockerfile: Dockerfile
    container_name: devkh-media-service
    volumes:
      - /usr/bin/ffmpeg:/usr/bin/ffmpeg
      - /usr/bin/ffplay:/usr/bin/ffplay
      - /usr/bin/ffprobe:/usr/bin/ffprobe
    ports:
      - "8095:8095"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/


  instructor-service:
    build:
      context: ./instructor-service
      dockerfile: Dockerfile
    container_name: devkh-instructor-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/


  student-service:
    build:
      context: ./student-service
      dockerfile: Dockerfile
    container_name: devkh-student-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/

  reward-service:
    build:
      context: ./reward-service
      dockerfile: Dockerfile
    container_name: devkh-reward-service
    ports:
      - "8091:8091"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: stage
      SPRING_CONFIG_IMPORT: configserver:http://139.59.252.233:8888/

  redis7001:
    image: redis:latest
    container_name: redis7001
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./7001/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./7001/data:/data
    ports:
      - "6379:6379"
    logging:
      options:
        max-size: '100m'
        max-file: '10'

  zipkin-server:
    image: openzipkin/zipkin:latest
    container_name: zipkin-server
    restart: always
    mem_limit: 1024m
    environment:
      - STORAGE_TYPE=mem
    expose:
      - '9411'
    ports:
      - '9411:9411'